name = "black-and-white"
main = "src/index.js"
compatibility_date = "2024-06-04"

[assets]
directory = "./public"

[[kv_namespaces]]
binding = "BLACK_AND_WHITE_LEADERBOARD_KV"
id = "70ea8dfb425f47c49bb16d5c85e2548a"

